[env:esp32]
board = esp32dev
framework = arduino
platform = espressif32
monitor_speed = 1115200

lib_deps = 
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit BusIO
    